using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using SJInovacao.Acesso.Common.Security;
using SJInovacao.Acesso.Modules.UserAccess.Domain.Entities;
using SJInovacao.Acesso.Modules.UserAccess.Infrastructure.ORM;
using System.Text;

class Program
{
    static async Task Main(string[] args)
    {
        if (args.Length > 0 && args[0] == "generate-permissions")
        {
            await GeneratePermissionsFile();
            return;
        }

        var host = Host.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration((hostingContext, config) =>
            {
                config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
            })
            .ConfigureServices((context, services) =>
            {
                services.AddDbContext<DefaultContext>(options =>
                    options.UseNpgsql(
                        context.Configuration.GetConnectionString("DefaultConnection"),
                        npgsqlOptions =>
                        {
                            // Define que as migrações estão no assembly do projeto Database
                            npgsqlOptions.MigrationsAssembly("SJInovacao.Acesso.Database");
                        }));
            })
            .Build();

        using var scope = host.Services.CreateScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<DefaultContext>();

        // Aplica as migrações pendentes ao banco
        dbContext.Database.Migrate();

        Console.WriteLine("Migrações aplicadas com sucesso!");

    }

    static async Task GeneratePermissionsFile()
    {
        Console.WriteLine("Gerando arquivo de permissões...");

        var basePath = AppContext.BaseDirectory;
        var configuration = new ConfigurationBuilder()
            .SetBasePath(basePath)
            .AddJsonFile("appsettings.json", optional: false)
            .Build();

        var connectionString = configuration.GetConnectionString("DefaultConnection");

        var optionsBuilder = new DbContextOptionsBuilder<DefaultContext>();
        optionsBuilder.UseNpgsql(connectionString, npgsqlOptions =>
            npgsqlOptions.MigrationsAssembly("SJInovacao.Acesso.Database"));

        await using var dbContext = new DefaultContext(optionsBuilder.Options);

        var permissions = await dbContext.Set<Permission>()
            .OrderBy(p => p.Name)
            .Select(p => p.Name)
            .ToListAsync();

        

        var userGroup = await dbContext.Set<GroupPermission>()// GroupPermissions
               .Include(u => u.Permissions).Select(g => new
               {
                   Groups = g.Name,
                   Permissions = g.Permissions.Select(p => p.Name).ToList()
               })
             .ToListAsync();


        if (permissions.Count == 0)
        {
            Console.WriteLine("Nenhuma permissão encontrada. Nada será gerado.");
            return;
        }

        var outputFile = @"C:\projetos\Gestao_de_Aplicativos\Projeto Gestao\SJInovacao.Acesso\src\SJInovacao.Acesso.Crosscutting\Security\Authentication\Permissions.g.cs";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by SJInovacao.Acesso.Database – do not edit manually.");
        sb.AppendLine("//   Run: dotnet run --project src/SJInovacao.Acesso.Database -- generate-permissions");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("namespace SJInovacao.Acesso.Common.Security.Authentication");
        sb.AppendLine("{");
        sb.AppendLine("    public static class SegurityPermissions");
        sb.AppendLine("    {");
       
        foreach (var group in userGroup)
        {
            var constName = NormalizePermissionName(group.Groups);
            sb.AppendLine($"        public const string Group{constName} = \"{group.Groups}\";");
            foreach (var perm in group.Permissions)
            {
                constName = NormalizePermissionName(perm);
                sb.AppendLine($"        public const string {constName} = \"{perm}\";");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        var directory = Path.GetDirectoryName(outputFile) ?? string.Empty;
        if (!Directory.Exists(directory))
            Directory.CreateDirectory(directory);

        await File.WriteAllTextAsync(outputFile, sb.ToString(), Encoding.UTF8);
        Console.WriteLine($"Permissões geradas com sucesso em: {outputFile}");
    }

    static string NormalizePermissionName(string name)
    {
        // Divide por pontos, hífens, underscores ou espaços
        var parts = name.Split(new[] { '.', '-', '_', ' ' }, StringSplitOptions.RemoveEmptyEntries);
        var pascalParts = parts.Select(p => char.ToUpper(p[0]) + p.Substring(1).ToLower());
        return string.Concat(pascalParts);
    }
}