// <auto-generated>
//   Generated by SJInovacao.Acesso.Database – do not edit manually.
//   Run: dotnet run --project src/SJInovacao.Acesso.Database -- generate-permissions
// </auto-generated>
namespace SJInovacao.Acesso.Common.Security.Authentication
{
    public static class SegurityPermissions
    {
        public const string GroupAdmPermission = "adm.permission";
        public const string UserUpdate = "user.update";
        public const string UserCreater = "user.creater";
        public const string GroupAdmDesativar = "adm.desativar";
        public const string UserDesativar = "user.desativar";
        public const string UserDelete = "user.delete";
    }
}
